- cloudrequestlog/middleware.go
If the (*Logger).Check method returns nil, it means that the entry
should not get logged.
> fix(cloudrequestlog): handle nil-result of Check correctly

- go.mod
- go.sum
- feat: move runtime config into cloudruntime package
- feat: remove cloudtesting.WithLogger
- chore(deps): bump opentelemetry-operations-go
> bump operations

- cloudpubsub/httphandler.go
- cloudpubsub/httphandler_test.go
- pubsubhttphandler.go
- feat: add cloudpubsub.NewHTTPHandler
- feat: add cloudrunner.PubsubHTTPHandler top-level method
> pubsub http handler

- Makefile
- README.md
- run.go
- tools/snippet/rules.mk
- tools/snippet/snippet.bash
- fit(run): output usage to stdout
- doc: tool for updating README with usage
> auto usage

- cloudrequestlog/middleware.go
If the downstream handler would mutated the request, the logged request
will not match what the user actually requested.
Prevents this by cloning the message before passing it down.
> fix(cloudrequest): ensure logging incoming request and not a potential mutated one

- .sage/go.mod
- .sage/go.sum
- Makefile
> chore(deps): bump sage

- cloudclient/dial.go
As documented in https://cloud.google.com/run/docs/troubleshooting - to
mitigate "connection reset by peer" and similar issues.
> feat(cloudclient): enable keepalive by default

- cloudmonitoring/exporter.go
When stopping the OpenTelemetry Cloud Monitoring exporter, it tries to export metrics a final time. This may be too close in time to the previous export, causing a failure of exporting too frequently:
> rpc error: code = InvalidArgument desc = One or more TimeSeries could
> not be written: One or more points were written more frequently than
> the maximum sampling period configured for the metric.
While it's not optimal to lose the last <=1 minute of metrics, it shouldn't trigger an Error log as it is not really actionable. Thus, demoting this log to Warn instead in this specific case.
> fix(cloudmonitoring): demote stop Error log to Warn on InvalidArgument

- cloudrequestlog/codetolevel.go
- cloudrequestlog/middleware.go
- go.mod
- go.sum
Exposes the default code->level transformation for other request loggers
to hook into.
> feat(cloudrequestlog): expose CodeToLevel

- .sage/main.go
Not working at the moment. To be enabled again when we find out what the
problem is
> fix: disable go-licenses

- cloudmonitoring/exporter.go
The OpenCensus bridge does not support all features from OpenCensus,
for example custom samplers which is used in some libraries.
The bridge presumably falls back to the configured sampler, so
this error can be ignored.
See
https://pkg.go.dev/go.opentelemetry.io/otel/bridge/opencensus
> fix(cloudmonitoring): silence unsupported sampler error

- cloudmonitoring/exporter.go
- cloudotel/errorhandler.go
- cloudotel/metricexporter.go
- cloudotel/traceexporter.go
- cloudtrace/exporter.go
- run.go
- refactor(cloudmonitoring): move MetricExporter to cloudotel
- refactor(cloudtrace): move TraceExporter to cloudotel
- refactor(cloudotel): move error handler from metric exporter
> refactor otel

- run.go
Recover panic from service and log as error before termination.
> feat(cloudrunner): recover panic

- go.mod
- go.sum
Forgot to bump this dependency as well
> feat: bump opentelemetry detectors to v1.16.0

- cloudprofiler/profiler.go
The profiler is enabled by default when calling cloudrunner.Run() but
fails if deploy in a Cloud Run Jobs environment as it only looks for
Cloud Run service environment variables
> feat: add support for Cloud Run Jobs profiling

- cloudconfig/yaml.go
The spec for a Cloud Run Job is a bit different from the service spec, so this isn't the prettiest solution but it works.
Here is the specification for a job:
https://cloud.google.com/run/docs/reference/yaml/v1#job
> feat(cloudconfig): support validating Cloud Run Jobs

- README.md
- cloudotel/metricexporter.go
- cloudotel/traceexporter.go
- cloudtrace/exporter.go
- go.mod
- go.sum
- run.go
- run_test.go
relates to [PE-963](https://einride.atlassian.net/browse/PE-963)
BREAKING CHANGE: removed SHUTDOWNDELAY feature
[PE-963]: https://einride.atlassian.net/browse/PE-963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix!: shutdown otel resource before exiting

- README.md
- cloudrequestlog/additionalfields.go
- cloudrequestlog/config.go
- cloudrequestlog/middleware.go
- cloudrequestlog/migration.go
- examples/cmd/http-server/main.go
Part of ongoing migration from zap to slog.
> feat(cloudrequestlog): migrate HTTP requests to slog

- cloudrequestlog/additionalfields.go
- cloudrequestlog/middleware.go
BREAKING CHANGE: Migrated from zap.Field to slog.Attr.
> feat(cloudrequestlog): migrate AdditionalFields.AppendTo to slog

- cloudotel/traceexporter.go
Even if the trace exporting is not enabled, we should always extract and
propagate traces between services.
> feat(cloudotel): always install text map propagator

- httpserver.go
A few http shutdown changes:
* disable keep alive
* set a limit on waiting for graceful shutdown
> HTTP shutdown

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .sage/go.mod
- .sage/go.sum
> feat: sage v0.370.0

- httpserver.go
From the docs of `Shutdown`:
> When Shutdown is called, [Serve], [ListenAndServe], and
> [ListenAndServeTLS] immediately return [ErrServerClosed]. Make sure the
> program doesn't exit and waits instead for Shutdown to return.
We don't do this and instead return from `ListenHTTP` immediately, in effect usually shutting down the calling service immediately without giving ongoing requests any chance to finish processing.
Note that [cloudmux.ServeGRPCHTTP](https://github.com/einride/cloudrunner-go/blob/master/cloudmux/mux.go#L43) does the right thing already by waiting for `httpServer.Shutdown` to complete. I changed the context timeout to 5 seconds to match what we are doing there.
> fix: wait for Shutdown to return before returning from ListenHTTP
