- logger.go
Adding a logger to the context manually should not need to be part of
the happy-path top-level API, given that we want to keep the top-level
API small and simple.
For unit tests, or other special-cases, one can use
`cloudzap.WithLogger` or `cloudtesting.WithLogger` from the subpackages.
> feat: remove cloudrunner.WithLogger

- cloudclient/config.go
- run.go
The GRPC_GO_RETRY environment variable *must* curretly be set to `"on"`
for retries to be enabled.
By cross-checking this variable with the config to enable client
retries, we exit with an error if the user has tried to enable retries
without setting this flag.
>  feat: error if retries are not successfully enabled

- README.md
- cloudtrace/exporter.go
OpenTelemetry traces every single request by default so we set a default
probability of 1% which is a good production default and also allow
setting the timeout for tracing with a default of 10 seconds
(OpenTelemetry has a default of 5 seconds)
> feat: add support for specifying tracing probability and timeout

- clouderror/wrap.go
- clouderror/wrap_test.go
Currently when wrapping errors containing codes `Unauthenticated` and
`PermissionDenied` they're wrapped in `codes.Internal`. These are both
client errors that should be communicated.
Check for these codes and preserve them.
> feat: preserve auth errors in cloudrunner.WrapTransient

- .github/workflows/ci.yml
> fix(ci): allow dependabot to make releases

- README.md
- cloudclient/config.go
With factor 1.3, the last attempt (5) will wait **at most** 0.75s before
retrying. In practice, this wait time will be much lower, because the
wait time is sampled from a random distribution `random(0,
max_wait_time)`.
The effect is that all retries are attempt very quickly, meaning that
the system on other side of RPC call might not have time to become
available again.
This commit changes the default backoff factor to 2. With this
configuration the last attempt (5) will wait **at most** 6.4s before
retrying. This should give the called RPC ample time to recover.
> fix(cloudclient): increase default backoff factor to 2

- .sage/go.mod
- .sage/go.sum
- cloudmux/mux.go
- cloudmux/mux_test.go
- go.mod
- go.sum
In some scenarios you may want to have both `HTTP` and `gRPC` at the same time and due to how Cloud Run works, you may have to use a single port to serve both protocols.
This particular feature has been in use in various production projects in internal Einride projects for quite some time now and should be considered fairly stable.
> feat: allow for serving `gRPC` and `HTTP` on the same port

- cloudrequestlog/httpresponsewriter.go
The normal HTTP `ResponseWriter` implements this interface, so let's expose that to users of our wrapper.
Useful for flushing streaming responses.
> feat(cloudrequestlog): implement `http.Flusher`

- README.md
- cloudmonitoring/metricmiddleware.go
- dialservice.go
- go.mod
- grpcserver.go
- run.go
Starts the already implemented metric exporter in `cloudrunner.Run`, and starts collecting metric from gRPC servers and clients initialized via this package.
Waiting for a release including https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1546 being cut.
> request metrics

- README.md
- cloudmonitoring/exporter.go
Exporting metric requires GCP `monitoring.googleapis.com` service to be
enabled, or it will continously error.
Changing the default behavior to disable exporting of metrics means it
is safe for users of this library to bump versions without errors.
> fix: disable exporter by default on GCE

- cloudrequestlog/httpresponsewriter.go
I.e. allow users of the cloudrequestlog to also use the hijack func if the underlying ResponseWriter implements it.
Useful for implementing for example websockets.
> feat(cloudrequestlog): proxy http.Hijack

- .sage/go.mod
- .sage/go.sum
- cloudmux/mux.go
- muxserver.go
Batteries now include gRPC and HTTP muxing.
> feat: add cloudrunner.ListenGRPCHTTP

- .github/workflows/ci.yml
- .github/workflows/release.yml
- cloudruntime/version.go
- cloudruntime/version_test.go
- go.mod
- go.sum
- run.go
Should be able to completely replace the current way of attaching custom
version strings to the build via linker flags.
> feat: add support for debug.BuildInfo

- cloudconfig/envconfig.go
- cloudconfig/zap.go
- examples/cmd/additional-config/main.go
Annotating config fields as secret prevents them from being logged.
> feat(cloudconfig): add support for secret annotation

- cloudyaml/doc.go
- cloudyaml/doc_test.go
- cloudyaml/testdata/example.yaml
- go.mod
- go.sum
Resolves the config for a Cloud Run service from a YAML service
specification file, including looking up secrets.
Can be used to simplify running services locally that depend on secrets.
> feat(cloudyaml): add ResolveEnvFromFile

- cloudtrace/idhook.go
- run.go
Makes cross-project trace investigations easier in joined log buckets.
> feat: add standard traceId log attribute

- cloudrequestlog/middleware.go
For http server request logs, the change will make sure a status of 200 is set if no explicit reponse status was set on the httpResponseWriter
> fix(http-request-logger): log the status field in the httpRequest object for 200 status

- cloudtrace/metadata.go
- cloudtrace/metadata_test.go
- cloudtrace/middleware.go
- trace.go
Currently the trace context is read from incoming metadata which is
only populated when the server is called via gRPC. This means there is
no way (see note 1) to read the trace context from a http server (as
incoming metadata is not populated.
---
This commit introduces a separate context.Context value which is populated
by middlewares and accessible for both HTTP and gRPC servers.
The old method is deprecated and replaced with Get/Set Context funcs.
---
Note 1: Technically you can access the trace context in a http server by
reading outgoing metadata, but that is not ideal.
> feat: add method for accessing trace context from http

- cloudpubsub/httphandler.go
According to [spec](https://cloud.google.com/pubsub/docs/push) PubSub works by sending a `POST` request
We shall filter others :D
> fix(pubsub): filter on POST requests to abide spec

- cloudclient/dial.go
While trying to run a backend service locally (with SA impersonation) and calling other internal backend services, I encountered an error like this:
```
idtoken: credential must be service_account, found "impersonated_service_account"
```
While google's `google-api-go-client` is not supporting using Application Default Credentials (via the employee account auth), there seems to be a workaround mentioned in [the issue](https://github.com/googleapis/google-api-go-client/issues/873) and here we basically implement the same.
Tested this locally while using it and it seems working correctly.
> feat(cloudclient): support id_token with impersonated_service_account type

- cloudclient/middleware.go
- cloudclient/middleware_test.go
grpc-go recently (July 2022) changed the error messages
for unknown content types, which was matched in this package.
Instead of exactly matching against the messages, and parsting
the status code with a regexp, the middleware makes a simpler search.
The changes in grpc-go can be seen here
https://github.com/grpc/grpc-go/pull/4474/files
> fix(cloudclient): make string matching more resilient

- cloudclient/dial.go
- grpcserver.go
With the current client keep alive settings, the server will
send GOAWAY to the client, as it is pinging too often and doing so
without an active stream.
This is because the default values for the server enforcement policy is
currently set to max one ping per 5min and no pings without active
streams.
This commit
* increases the time between pings from a client to 1 minute, as this
should be sufficient to avoid gateway reaping the connection.
* decreases the server min time enforcement policy to 30s (was
defaulting to 5min)
* configure server to allow client to send pings even if no stream is
active.
> fix: align keepalive settings between client and server

- cloudrequestlog/codetolevel.go
- cloudrequestlog/middleware.go
It is often not desireable to have debug logs in production however today it is not possible to disable debug logs without also disabling request logs from requests with an OK status.
BREAKING CHANGE: Changed OK logs to be written at INFO level
> feat!: change request logs from OK status to INFO level

- .sage/main.go
> fix: add dot to go comment on Sage

- cloudtrace/exporter.go
Should be unique, recommended to use package name of the
instrumentation.
> fix(cloudtrace): specify name for bridge tracer

- cloudrequestlog/middleware.go
Log as warning to not trigger error log alerting.
> fix(cloudrequestlog): don't log 503 as error

- cloudclient/dial.go
As this https://github.com/googleapis/google-api-go-client/pull/1792 has been merged as released in google api 0.106, we don't need this bunched of code anymore.
Tested with a backend service using impersonated account and the service can load up nicely locally.
> chore(dailer): remove special handlers for impersonated SA

- cloudmonitoring/metricmiddleware.go
- cloudrequestlog/middleware.go
- cloudserver/middleware.go
- cloudstream/middleware.go
- cloudtrace/middleware.go
- cloudzap/middleware.go
- grpcserver.go
The ones used for unary calls are ported over for streaming RPCs. This allows you to use all your familiar contextual tools, such as metrics, tracing, logging etc.
> feat(grpc): add stream middleware interceptors

- cloudserver/security_headers.go
- httpserver.go
- run.go
Add middleware adding security-related headers.
I didn't add this middleware to the server returned from `NewHTTPServer` since it could be a breaking change.
> feat: add security headers middleware

- cloudmux/mux.go
`buf curl` sends the content-type as application/grpc+proto and you cannot change it. This gets interpreted as HTTP without this fix.
> fix(cmux): match grpc if grpc+proto content type

- .github/dependabot.yml
These updates generally need to be bumped together, and this should take care of that.
> ci(dependabot): group opentelemetry updates to a single PR

- README.md
- cloudotel/metricexporter.go
For some Google Cloud libraries, metrics are emitted that are useful to understanding the operation of a service but they are using the OpenCensus SDKs rather than the OpenTelemetry ones.
A notable example is GoogleCloudPlatform/cloud-sql-go-connector which is used as a proxy when connecting Cloud Run instances to Cloud SQL. There is a [suite of metrics](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/v1.4.5/internal/trace/metrics.go) that are particularly useful in monitoring the health of the proxy.
This change allows users to enable capturing OpenCensus formatted metrics using the OpenTelemetry bridge shim. By default this will be disabled.
There is a downside to enabling this producer, mainly that since OpenCensus telemetry uses globals, installing a bridge will …
> feat: enable collection of OpenCensus metrics

- cloudrequestlog/codetolevel.go
Not an error actionable by the service owner.
> feat(cloudrequestlog): map Unimplemented to Warning

- cloudmonitoring/metricmiddleware.go
- cloudotel/metricexporter.go
- go.mod
- go.sum
otel uses a little bit of a strange versioning schema, where the
contracts are versioned under otel/semconv/{VERSION}, but the package
can be upgraded to several versions ahead of the contract. This has
worked fine for our use-cases, but we recently ran into a problem where
we go the following error on application startup - after a dependabot
upgrade came along:
```
cannot merge resource due to conflicting Schema URL
```
This led down a rabbit hole, eventually finding out this quirk in otel
usage.
BREAKING CHANGE: This upgrades the version of the otel contract being
used. This is possibly a breaking change so care must be taken so that other OTEL packages are upgraded to v1.21 simultaneously so there aren't further breakages.
> feat!: upgrade to latest stable otel API v1.21.0

- README.md
- run.go
- run_test.go
This adds an artifical shutdown delay, in order to allow a service to
stop receiving requests before it cancells its root context. This is
completely opt-in, and the added context cancellation delay will not be
added if no duration is configured.
> feat: add ShutdownDelay configuration

- cloudclient/dial.go
- cloudclient/dialinsecure.go
- cloudmux/mux_test.go
- cloudserver/middleware_test.go
Bumps the all group with 4 updates: [golang.org/x/net](https://github.com/golang/net), [golang.org/x/oauth2](https://github.com/golang/oauth2), [golang.org/x/sync](https://github.com/golang/sync) and [google.golang.org/grpc](https://github.com/grpc/grpc-go).
Updates `golang.org/x/net` from 0.22.0 to 0.24.0
- [Commits](https://github.com/golang/net/compare/v0.22.0...v0.24.0)
Updates `golang.org/x/oauth2` from 0.18.0 to 0.19.0
- [Commits](https://github.com/golang/oauth2/compare/v0.18.0...v0.19.0)
Updates `golang.org/x/sync` from 0.6.0 to 0.7.0
- [Commits](https://github.com/golang/sync/compare/v0.6.0...v0.7.0)
Updates `google.golang.org/grpc` from 1.62.1 to 1.63.0
- [Release notes](https://github.com/grpc/grpc-go/releases)
- [Commits](https://github.com/grpc/grpc-go/compare/v1.62.1...v1.63. …
> chore(deps): bump the all group with 4 updates

- cloudconfig/yaml.go
Cloud Run now supports multi container deployments (up to 10 per instance).
With this change, sidecar container defined environment variables are not set for the ingress container.
Official docs: https://cloud.google.com/run/docs/deploying\#multicontainer-yaml
> feat(cloudconfig): support multi container configuration

- clouderror/wrap.go
- clouderror/wrap_test.go
Ensures i/o timeouts are forwarded as DeadlineExceeded transient errors
to callers, which in turn ensures these errors are retried automatically.
> feat: handle i/o timeouts as transient timeout errors

- cloudotel/metricexporter.go
The periodic reader collects and exports metrics previously recorded at
a given interval.
In order to make sure we do not miss recorded metrics that have not yet
been exported at shutdown, we need to call the reader's Shutdown method
which performs a last collect and export.
It also performs a shutdown of the exporter so we don't need to do that
ourselves.
relates to [PE-910](https://einride.atlassian.net/browse/PE-910)
[PE-910]: https://einride.atlassian.net/browse/PE-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(cloudotel): call reader.Shutdown instead of exporter.Shutdown

- cloudotel/resource.go
On Cloud Run Job opentelemetry sets the "task_id" to the job instance id
which leads to high cardinality as it changes for every run.
In order to avoid that we override it with the cloud run task index
instead.
relates to [PE-910](https://einride.atlassian.net/browse/PE-910)
[PE-910]: https://einride.atlassian.net/browse/PE-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: override otel "task_id" for cloud run job

- cloudotel/metricexporter.go
Currently investigating underlying cause for failing the final metric
export.
The previous change enabled metric export on shutdown to happen -
previously it has not been triggered in the first place - so we are not
missing any metrics that we haven't already been missing.
> fix(cloudotel): downgrade metric export error to warning

- cloudotel/metricexporter.go
The provider will handle shutting down it's resources, including the
reader.
relates to [PE-910](https://einride.atlassian.net/browse/PE-910)
[PE-910]: https://einride.atlassian.net/browse/PE-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: shutdown otel metrics provider

- clouderror/wrap.go
- clouderror/wrap_test.go
This reverts commit d62a6a3d8fea45a88ff391fecdd207dfc3dc47d2.
This commit breaks the API description of only forwarding transient
(retryable) errors.
> revert: "feat: preserve auth errors in cloudrunner.WrapTransient"

- cloudslog/context.go
- cloudslog/context_test.go
- cloudslog/handler.go
For feature-parity with Zap logger.
> feat(cloudslog): add context-based attributes

- cloudrequestlog/additionalfields.go
- logger.go
Step 1 is to change the public API in a backwards-compatible way so that
both slog and zap logger fields/attributes are supported. This is part
of step 1.
Step 2 is to change the underlying representation from zap to slog -
this will come in a follow up.
The conversion code is copied from the stdlib and the zap library.
> feat(cloudrequsetlog): initial slog support

- cloudrequestlog/codetolevel.go
- cloudrequestlog/middleware.go
BREAKING CHANGE: The API now returns a slog.Level instead of
zapcore.Level.
> feat(cloudrequestlog): migrate CodeToLevel to slog

- cloudslog/redact.go
- cloudslog/redact_test.go
Due to a bug, messages with redacted fields were having all string
fields redacted.
> fix(cloudslog): don't over-redact fields

- cloudtrace/middleware.go
Commit 0aeada65cb3721447da341d679bce38d2dd3d139 accidentally removed
trace field on log statements written with the request logger.
This commit reverts parts of that commit, such that zap request logger
still has the trace field populated.
> fix(cloudtrace): re-add trace logger fields for zap

- cloudslog/handler.go
- run.go
according to https://cloud.google.com/trace/docs/trace-log-integration
The trace field must be set to a string with the following format:
> projects/PROJECT_ID/traces/TRACE_ID
> feat(cloudslog): include projectID into trace

- .sage/main.go
- cloudotel/traceidhook.go
- cloudotel/tracemiddleware.go
- cloudpubsub/httphandler.go
- cloudtesting/trace.go
- cloudtrace/doc.go
- go.mod
- go.sum
- grpcserver.go
- httpserver.go
- options.go
- run.go
- trace.go
Pass a context that contains trace information extracted from the incoming message, allowing traces to span from publishers over to subscribers.
In order for publishers to include tracing information, the pubsub client should be created with:
```go
client, err := pubsub.NewClientWithConfig(
ctx,
cloudrunner.Runtime(ctx).ProjectID,
&pubsub.ClientConfig{
EnableOpenTelemetryTracing: true,
},
```
Depends on https://github.com/googleapis/google-cloud-go/pull/10827 which is included in [v1.43.0](https://github.com/googleapis/google-cloud-go/releases/tag/pubsub%2Fv1.43.0).
> feat(pubsub): extract trace information

- README.md
- cloudotel/tracemiddleware.go
- cloudotel/tracemiddleware_test.go
- cloudpubsub/httphandler.go
- cloudpubsub/payload.go
- cloudruntime/config.go
- cloudruntime/env.go
- cloudruntime/env_test.go
- run.go
this ensures that tracing from the pubsub message is properly propagated before we create a context with log tracing. Without this fix, the cloudrequestlog middleware logs incorrectly and incorrect traceId is attached to the slog field with TraceHook.
There’s no reliable way to determine whether the request originates from pubsub without attempting to decode it. I could make this configurable to avoid propagating the trace when it's not wanted.
Let’s discuss if you have any better ideas for addressing this!
> fix(trace): propagate trace from pubsub msg

- cloudpubsub/httphandler.go
The AuthenticatedHTTPHandler wraps HTTPHandler and verifies that the there is a valid Google-signed bearer token in the Authorization header. Optionally also verifies a user specified audience and email token claim.
> feat(pubsub): introduce authenticated pubsub handler
